//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int snum { get; set; }
        public string sname { get; set; }
        public string sloc { get; set; }
        public int mall_id { get; set; }
    
        public virtual Mall Mall { get; set; }
    }
}
